version: '2.0'
services:
    frontend:
        image: frontApp
        build:
            context: frontend
            dockerfile: Dockerfile
        ports:
            - 8081:3000
    backend:
        image: backApp
        build:
            context: backend
            dockerfile: Dockerfile
        ports:
            - 8080:8080