version: '2.0'
services:
    frontend:
        image: myfrontend_chipichipi
        build:
            context: frontend
            dockerfile: Dockerfile
        ports:
          - 8081:3000
    backend:
        image: mybackend_chapachapa
        build:
            context: backend
            dockerfile: Dockerfile
        ports:
            - 8080:8080